baseURL = "https://lifeofdan.github.io"
languageCode = "en-us"
title = "lifeofdan"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "A pretty self-explanatory blog."
  logo = "/img/my-avatar.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Dan"
  website = "lifeofdan.me"
  email = "contact@lifeofdan.me"
  github = "lifeofdan"
# reddit = "username"
  youtube = "user/CorazineDru" # or channel/channelname

[[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    identifier = "christianity"
    name = "Christianity"
    weight = 3

 [[menu.main]]
    parent = "christianity"
    name = "Bible Studies"
    url = "bible-studies/"
    weight = 1

 [[menu.main]]
    parent = "christianity"
    name = "Communion Meditations"
    url = "communion/"
    weight = 2

 [[menu.main]]
    parent = "christianity"
    name = "sermons"
    url = "sermons/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5